### ISSUE TITLE
Should CUSTOM_EPOCH be 1401277473000 ?

### ISSUE THREAD

**Issue by Felix0114** [intenthq/icicle#16]
in generateIdsUsingRedis(final Redis redis, final long batchSize) 

long id = ((timestamp - CUSTOM_EPOCH) << TIMESTAMP_SHIFT)
          | (logicalShardId << LOGICAL_SHARD_ID_SHIFT)
          | i;

The timestamp is in milliseconds. Assume that CUSTOM_EPOCH is in milliseconds.
1401277473(ms) is just about 16 days. Compare to normal unix epoch, this setting only extends 16 days.

**Comment by nathankleyn** [comment]
@Felix0114 The custom epoch is a UNIX timestamp (in milliseconds) which corresponds to:

> Wed, 28 May 2014 11:44:33 GMT

The idea is that, to allow you to store the time in less "bits", you can start the epoch from `0` again at some point. When we first made this project, we set that epoch at the date above. So rather than thinking about it as a range, it's more a "we pretend the epoch is 0 again from here".

So for example, right now the UNIX time for me is `1454668344`. If I subtract our custom epoch from that of `1401277473`, I'm left with `53390871`. In binary, this is `11001011101010111000010111`, which is only 26-bits. We have allowed for up to 41 bits for time. This gives us a range of about ~69 years from the date of that custom epoch above.

**Comment by Felix0114** [comment]
I know how custom epoch works. The question which I want to point out is that the ***timestamp*** is in milliseconds in the source code. 
`long timestamp = (icicleRedisResponse.getTimeSeconds() * ONE_MILLI_IN_MICRO_SECS)
        + (icicleRedisResponse.getTimeMicroseconds() / ONE_MILLI_IN_MICRO_SECS); `
But CUSTOM_EPOCH is defined in seconds.

You subtract them in different units. 
`long id = ((timestamp - CUSTOM_EPOCH) << TIMESTAMP_SHIFT)
| (logicalShardId << LOGICAL_SHARD_ID_SHIFT)
| i;`

in the example which you provided,
the ***timestamp*** variable might be 1454668344000, and  CUSTOM_EPOCH is 1401277473,
(timestamp - CUSTOM_EPOCH) = 1453267066527,  not 53390871.

By the way, would you provide some ways to setup  CUSTOM_EPOCH in the future?

**Comment by nathankleyn** [comment]
@Felix0114 Oh my goodness, you are absolutely right. :cry: 

I'm just going to have a think about how we can address this issue - we can't just change the epoch to what it should be in the case of people who are using this (as the IDs would eventually collide). I think the right thing to do will be something like:

* Fix the issue with the default epoch.
* Add the ability to set the epoch via config (so people who are migrating can keep the existing epoch so there's no collisions).
* Bump the major version.

I'll have a think about this today and get back to you. Really good spot, thanks for the report - I'll make sure to credit you on any work that gets done as this is a big deal and we really appreciate it! :+1:

**Comment by nathankleyn** [comment]
@Felix0114 There's a branch with a preview of some of the changes at [`fix-incorrect-epoch-start`](https://github.com/intenthq/icicle/tree/fix-incorrect-epoch-start). I'll continue updating this, which will subsequently become the v2.0 release soon-ish. :+1:

**Comment by Felix0114** [comment]
Good to hear. :+1:
