### ISSUE TITLE
How the "fewer ids" happen?

### ISSUE THREAD

**Issue by kran** [intenthq/icicle#5]
>When requesting a batch of IDs, the generator cannot always return you the amount you asked for (this is a limitation related to our strong uniqueness guarantees) - instead, it will return between 1 and n, where n is the number of IDs you asked for in the batch. 

The document says this, and then I read the code but can't find which step will make this happen. 
I must have missed something, could you show me that ?

Thanks.

**Comment by janstenpickle** [comment]
Hi @kran 

It's because for each millisecond per server the portion of the ID which increments within that millisecond allows up to 4096. It's the part labelled sequence in the image below:

![The ID structure, in the format ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCDDDDDDDDDDDD](https://raw.githubusercontent.com/intenthq/icicle/master/id-structure.png)

So if you have previously requested 4095 IDs within a millisecond for that server and you request 100, you will actually only get one, because that is all that is left in the sequence. If the sequence is exhausted (all 4096 IDs have been generated in the millisecond) the normal retry pattern will be followed, and another server will be asked.  

Hope this clears things up!

**Comment by kran** [comment]
Thank you janstenpickle!  
I understand that now.
